services:
  logisticsweb:
    image: ${DOCKER_REGISTRY-}logisticsweb
    build:
      context: .
      dockerfile: LogisticsWeb/Dockerfile
    ports:
    - "8080:8080"
    - "8081:8081"
    depends_on:
    - sqlserver
    environment:
    - ASPNETCORE_ENVIROMENT=Development
    networks:
    - productnetwork
    restart: on-failure
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment: 
      SA_PASSWORD: "abc@123!"
      ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"
    volumes:
    - sqlvolume:/var/opt/mssql
    networks:
    - productnetwork
networks:
 productnetwork:

volumes:
  sqlvolume:
